/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Games } from '../model/games';
import { Players } from '../model/players';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DevelopersService {

    protected basePath = 'https://virtserver.swaggerhub.com/dhrutijoshi348/oneForGames/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * searches for games
     * By passing in the appropriate options, you can search for available inventory in the system 
     * @param gameName pass an optional search string for looking up inventory
     * @param id number of records to skip for pagination
     * @param score maximum number of records to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchGames(gameName?: string, id?: number, score?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Games>>;
    public searchGames(gameName?: string, id?: number, score?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Games>>>;
    public searchGames(gameName?: string, id?: number, score?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Games>>>;
    public searchGames(gameName?: string, id?: number, score?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (gameName !== undefined && gameName !== null) {
            queryParameters = queryParameters.set('gameName', <any>gameName);
        }
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }
        if (score !== undefined && score !== null) {
            queryParameters = queryParameters.set('score', <any>score);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Games>>('get',`${this.basePath}/games`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * searches player
     * By passing in the appropriate options, you can search for available inventory in the system 
     * @param playerName pass an optional search string for looking up inventory
     * @param id number of records to skip for pagination
     * @param playerOn maximum number of records to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchPlayer(playerName?: string, id?: number, playerOn?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Players>>;
    public searchPlayer(playerName?: string, id?: number, playerOn?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Players>>>;
    public searchPlayer(playerName?: string, id?: number, playerOn?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Players>>>;
    public searchPlayer(playerName?: string, id?: number, playerOn?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (playerName !== undefined && playerName !== null) {
            queryParameters = queryParameters.set('playerName', <any>playerName);
        }
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }
        if (playerOn !== undefined && playerOn !== null) {
            queryParameters = queryParameters.set('Player-on', <any>playerOn);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Players>>('get',`${this.basePath}/players`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
